package apples

// cat redcards.txt| sed 's/ - /$/' | sed 's/"/\\"/g' | sed 's/    \(.*\)$\(.*\)/\t{Name: "\1", Description: "\2"},/'
var redCards = []*Card{
	{Name: "A Bad Haircut", Description: "The perfect start to a bad hair day."},
	{Name: "A Bull Fight", Description: "Also known as \"la fiesta brava\" (the brave festival). A whole lot of bull.."},
	{Name: "A Car Crash", Description: "\"Hey, it was an accident!\""},
	{Name: "A Cheap Motel", Description: "No charge for the cockroaches."},
	{Name: "A Crawl Space", Description: "Where you'll find something the cat dragged in."},
	{Name: "A Dozen Red Roses", Description: "When eleven just won't do."},
	{Name: "A Flat Tire", Description: "\"Whaddya mean, there's no spare?\""},
	{Name: "A Full Moon", Description: "\"When the moon hits your eye like a big pizza pie, that's amore!\" -Dean Martin"},
	{Name: "A Haunted House", Description: "Maybe if people would STOP building their dream homes on ancient burial grounds ..."},
	{Name: "A High School Bathroom", Description: "\"Fools rush in where angels fear to tread\" -Alexander Pope"},
	{Name: "A Honeymoon", Description: "America's top honeymoon spots are Hawaii, Niagara Falls, Las Vegas and Florida. You can get there by air, land, sea ... or shotgun."},
	{Name: "A Locker Room", Description: "Steamy atmosphere ... bawdy humor ... sweaty bodies ... HEY! Sounds like Cable TV!"},
	{Name: "A Morgue", Description: "\"Given strange eons, even death may die...\" -H.P. Lovecraft"},
	{Name: "A Nine Iron", Description: "A golf club best used on short shots or large opponents."},
	{Name: "A School Bus", Description: "The only thing we have to fear is fear itself. -Franklin D. Roosevelt"},
	{Name: "A School Cafeteria", Description: "Food fight!."},
	{Name: "A Sunrise", Description: "\"But he who kisses the joy as it flies/ Lives in eternity's sunrise.\" -William Blake"},
	{Name: "A Sunset", Description: "The sun never set on the British Empire ... because God didn't trust the English in the dark."},
	{Name: "A Tree House", Description: "Your first high-rise apartment."},
	{Name: "A Used Car Lot", Description: "One of the most honest places around. Honest ..."},
	{Name: "Abraham Lincoln", Description: "1809-65, 16th U.S. president, led the Union to victory in the American Civil War and abolished slavery. Was assassinated for his efforts."},
	{Name: "Adam Sandler", Description: "1966- , American comedian, film star, and Saturday Night Live alumnus. Genius or goofball - you make the call."},
	{Name: "Adolph Hitler", Description: "1889-1945, turned Germany into a militarized dictatorship, caused the slaughter of millions and launched World War II."},
	{Name: "AIDS", Description: "Acquired Immune Deficiency Syndrome."},
	{Name: "Airline Food", Description: "Since when is a bag of peanuts considered a meal?"},
	{Name: "Al Pacino", Description: "1940- , Oscar winning American actor and star of \"The Godfather,\" \"Dog Day Afternoon\" and \"Scent Of A Woman.\" One very intense guy."},
	{Name: "Albert Einstein", Description: "1879-1955, German-born American physicist and Nobel laureate who created theories of relativity. Nice hair."},
	{Name: "Alfred Hitchcock", Description: "1899-1980, British-born American director and producer of brilliant psychological thrillers. Right, mother? MOTHER!"},
	{Name: "Alien Abductions", Description: "There was a blinding light -and she was gone!"},
	{Name: "Americans", Description: "How many Americans does it take to screw in a light bulb? THAT'S NOT FUNNY! WE'RE SUING!"},
	{Name: "Amputations", Description: "\"A SCRATCH? Your arm's off!\" - Monty Python and the Holy Grail."},
	{Name: "Angry Hornets", Description: "Who put the bees in their bonnets?."},
	{Name: "Andy Warhol", Description: "1928-87, American painter and filmmaker, a leader of the pop art movement. Famous for slightly more than 15 minutes."},
	{Name: "Anne Frank", Description: "1929-45, German Jewish girl who wrote in her diary about her family hiding from the Nazis. She died in a concentration camp."},
	{Name: "Antarctica", Description: "Home to the lowest temperature ever recorded on earth, -126.9 F."},
	{Name: "Anthony Hopkins", Description: "1937- , British actor starred in The Elephant Man, Howard's End, and, of course, The Silence Of The Lambs. Knighted in 1992."},
	{Name: "Apple Pie", Description: "It's as American as ... as ... something ..."},
	{Name: "Apples", Description: "More than 40 million metric tons are produced worldwide every year. How 'bout them apples?"},
	{Name: "Armed Robbery", Description: "You got your Robbery, your Armed Robbery, your Strong Armed Robbery, and, of course, the five finger discount."},
	{Name: "Assembly Lines", Description: "Faster. FASTER!"},
	{Name: "At My Parent's House", Description: "Like never-never land, you're never seen as an adult here."},
	{Name: "Atlantis", Description: "Mythological city where the folks had that sinking feeling."},
	{Name: "Atomic Bombs", Description: "The Italian physicist Enrico Fermi succeeded in producing the first nuclear chain reaction in 1942, at the University of Chicago."},
	{Name: "Attack On Pearl Harbor", Description: "\"Yesterday, December 7th, 1941, a date which will live in infamy ...\" -Franklin D. Roosevelt"},
	{Name: "Austin Powers", Description: "Fictional British man of mystery. Yeah, bay-beee, yeah!"},
	{Name: "Australian Outback", Description: "Beware of dangerous temperatures, strange animals, and didgeridoos."},
	{Name: "Babe Ruth", Description: "1895-1948, American baseball legend, and one heck of a candy bar!"},
	{Name: "Babies", Description: "Little bundles of joy ... and who needs sleep, anyway?"},
	{Name: "Baby Showers", Description: "Baby showers may bring flowers ..."},
	{Name: "Backstreet Boys", Description: "The latest American pop boy band. Which one do you think is the cutest?"},
	{Name: "Bad Dogs", Description: "Bad dog, bad dog. What'cha gonna do?"},
	{Name: "Bagpipes", Description: "A shrill-toned musical instrument consisting of a leather bag and pipes. Also available in plaid."},
	{Name: "Baked Beans", Description: "Add a little bacon, brown sugar and Beano!"},
	{Name: "Baked Potatoes", Description: "Hot potato, couch potato, potato head, twice baked, half-baked, ... whatever."},
	{Name: "Baking Cookies", Description: "An experience only surpassed by eating them."},
	{Name: "Bald Eagles", Description: "Known for their majestic appearance and powerful flight. In 1782, the bald eagle was chosen as the emblem of the United States."},
	{Name: "Ballerinas", Description: "Beautiful, graceful dancers who are always on their toes."},
	{Name: "Bangkok", Description: "Capital of Thailand. Location: near the Gulf of Siam. Population: five million. Reputation: seedy."},
	{Name: "Bankruptcy", Description: "It'll be the debt of you."},
	{Name: "Barbara Walters", Description: "1931- , American television journalist and author. Voted one of the most important women of the century by \"Ladies Home Journal.\""},
	{Name: "Barbed Wire", Description: "Wire with sharp points, used for fences. Created havoc on the western frontier."},
	{Name: "Barfing", Description: "We didn't want to bring that up ..."},
	{Name: "Barney", Description: "Purple dinosaur. \"I love you, you love me, blah, blah, blah ... \""},
	{Name: "Bart Simpson", Description: "Fictional animated character. Don't have a cow, man!\""},
	{Name: "Bates Motel", Description: "The haunt of Alfred Hitchcock's psycho, Norman Bates ... and mother, of course ..."},
	{Name: "Batman", Description: "How does Batman's mother call him home? \"Dinner, dinner, dinner, dinner, dinner, dinner, dinner, dinner - BATMAN!\""},
	{Name: "Bats", Description: "The little brown bat consumes as many as 600 mosquitoes in an hour. The vampire bat dines elsewhere ..."},
	{Name: "Beach Parties", Description: "Up for some \"Beach Blanket Bingo,\" Annette?"},
	{Name: "Beanie Babies", Description: "Tiny plush collectibles to love and cherish. Don't take that tag off!"},
	{Name: "Beauty And The Beast", Description: "A tale as old as time ... so Disney didn't have to pay royalties."},
	{Name: "Beer", Description: "\"Beer is proof that God loves us and wants us to be happy.\" - Benjamin Franklin"},
	{Name: "Beer Bellies", Description: "Just think of them as microbreweries."},
	{Name: "Beethoven", Description: "1770-1827, German composer, considered one of the greatest of the western world."},
	{Name: "Beets", Description: "Beats Brussels sprout."},
	{Name: "Being In Love", Description: "\"Love's like the measles, all the worse when it comes late.\" -Douglas Jerrold"},
	{Name: "Bell-Bottoms", Description: "Bell-bottoms and pea coats -who would have thought the Navy could be such a trendsetter?"},
	{Name: "Ben Stiller", Description: "1965-, American actor, director, and funny guy of Reality Bites, There's Something About Mary, and Meet The Parents"},
	{Name: "Berlin, 1945", Description: "Adolph Hitler's last stand. Bunker ... I mean -hunker down, soldier."},
	{Name: "Big Bang Theory", Description: "A cosmological theory for the origin of the universe. An explosive idea!"},
	{Name: "Big Macs", Description: "T w o a l l b e e f p a t t i e s s p e c i a l s a u c e l e t t u c e c h e e s e p i c k l e s o n i o n s o n a s e s a m e s e e d b u n ."},
	{Name: "Bigfoot", Description: "Legendary North American monster, a.k.a. Sasquatch or the Abominable Snowman."},
	{Name: "Bill Clinton", Description: "1946- , popular, yet embattled, 42nd president of the United States."},
	{Name: "Bill Gates", Description: "1955-, chairman and chief software architect of Microsoft Corporation. A very rich guy."},
	{Name: "Bill Murray", Description: "1950-, American actor and comedian. Star of Ghostbusters, Stripes, Groundhog Day, and Lost In Translation."},
	{Name: "Billboards", Description: "Only 1,254 miles to Wall Drug ..."},
	{Name: "Bingo", Description: "\"There was a farmer, had a dog, and Bingo was his name-o ...\""},
	{Name: "Bird Watching", Description: "A hobby that relies on a wing and a prayer."},
	{Name: "Black Holes", Description: "The gravitational field of a black hole is so strong that nothing, including light, can escape from its vicinity."},
	{Name: "Black Velvet", Description: "Smooth, silky and sophisticated ... until you paint an Elvis on it."},
	{Name: "Blizzard", Description: "Extreme cold, strong winds, and a head snowfall. Also known as Canada."},
	{Name: "Blood", Description: "A healthy human body contains between five and six quarts of blood. Bloody right they do!"},
	{Name: "Board Games", Description: "Games have been played for thousands of years. Some games of Monopoly just SEEM that long."},
	{Name: "Body Odor$Over ", Description: "1.6 billion is spent each year on antiperspirants in the United States. That stinks!"},
	{Name: "Body Piercing", Description: "YOU STUCK WHAT? WHERE?"},
	{Name: "Body Surfing", Description: "When you're too cheap to buy a surfboard."},
	{Name: "Bonbons", Description: "Sweets for the sweet ..."},
	{Name: "Bongos", Description: "Small drums played with the fingers. Used in Latin American and African music. The choice of American beat poets."},
	{Name: "Bottled Water", Description: "How much are you willing to pay for something you can get for free?"},
	{Name: "Boxing", Description: "An ancient and honorable sport - not just for boys anymore ..."},
	{Name: "Boy Scouts", Description: "International organization for boys and young men founded in England in 1908, to foster character, citizenship and outdoor life."},
	{Name: "Boyfriends", Description: "\"My boyfriend's back and you're gonna be in trouble.\" - The Angels"},
	{Name: "Brad Pitt", Description: "1963- , American actor and heart-throb."},
	{Name: "Brain Surgeons", Description: "Hey, it ain't brain surgery ... oh ... wait a second ..."},
	{Name: "Brains", Description: "Vital to human existence and mad scientists."},
	{Name: "Britney Spears", Description: "1981-, American singer. From mouseketeer to international pop star."},
	{Name: "Broadway", Description: "The New York theater district. \"They say the neon lights shine bright on Broadway.\" -Barry Mann"},
	{Name: "Bruce Willis", Description: "1955- , Diehard American action movie star who has moonlighted on TV. He also starred in Pulp Fiction, Armageddon and The Sixth Sense."},
	{Name: "Bubble Gum", Description: "Crack it, snap it, pop it, and blow it!"},
	{Name: "Bubbles", Description: "\"Tiny bubbles, in the wine/ Tiny bubble make me feel fine ...\" -Don Ho"},
	{Name: "Bullwinkle", Description: "As in the cartoon \"The Adventures of Rocky and Bullwinkle\" - the moose half of moose and squirrel."},
	{Name: "Bumper Stickers", Description: "Your personal billboard!"},
	{Name: "Bungee Jumping", Description: "Another sport hanging on by a thread."},
	{Name: "Buying A House", Description: "If only we had the money, we could get a mortgage."},
	{Name: "Cabbage", Description: "From the French word caboche, meaning \"big head.\""},
	{Name: "Cactus", Description: "Require little care and exhibit bizarre forms. As such, they are often mistaken for Survivalists."},
	{Name: "California", Description: "Sacramento is its capital, Los Angeles its largest city. Here we come."},
	{Name: "Camping Trip", Description: "When you just have to get s'more nature."},
	{Name: "Canada", Description: "Federated country of North America. The Great White North - eh?"},
	{Name: "Canadians", Description: "How many Canadians does it take to screw in a lightbulb? Fifteen. Fourteen to chip it out of the ice, and one to screw it in."},
	{Name: "Captain Kirk", Description: "Fictional starship captain. \"Beam me up Scotty, there is no intelligent life on this planet!\" - bumper sticker, 1980s"},
	{Name: "Car Bombs", Description: "Not including the Ford Pinto, of course."},
	{Name: "Car Horns", Description: "Blow it, buddy!"},
	{Name: "Carl Sagan", Description: "1934-96, American astronomer and pioneer exobiologist. Touched many lives. Billions and billions of them."},
	{Name: "Carnival Workers", Description: "Step right up ..."},
	{Name: "Cary Grant", Description: "1904-86, British-born American actor known for his debonair manner. He can be found North by Northwest."},
	{Name: "Casablanca", Description: "The largest city in Morocco, and one heck of a good movie. \"Of all the gin joints in all the towns in all the world...\""},
	{Name: "Casinos", Description: "Slots and slots of fun."},
	{Name: "Castles", Description: "Kings, queens, knights in shining armor, and little square hamburgers."},
	{Name: "Caves", Description: "Stalactites, stalagmites. Which go up and which go down?"},
	{Name: "Celine Dion", Description: "1968-, Canadian singer whose heart will go on, and on ..."},
	{Name: "Cell Phones", Description: "Get off the phone or get off the road!"},
	{Name: "Cesar Chavez", Description: "1927-93, American labor leader who led the 1965 nationwide boycott of California grapes ... a bunch of sour grapes!"},
	{Name: "Chain Letters", Description: "Send this game to ten of your friends and good luck will follow. Honest!"},
	{Name: "Chains", Description: "Gold or iron: name your shackles."},
	{Name: "Challenger Explosion", Description: "\"Without a wish, without a will/ I stood upon that silent hill/ and stared into the sky ...\" - Ralph Hodgeson"},
	{Name: "Chameleons", Description: "The chameleon is a lizard that changes color when frightened -or is that a politician?"},
	{Name: "Charging Rhinos", Description: "How do you stop a rhino from charging? Take away its credit cards."},
	{Name: "Cheesecake", Description: "A really tasty dish."},
	{Name: "Cher", Description: "1946- , American singer and actor, she makes aging look good."},
	{Name: "Chicago", Description: "Third largest city in the United States. Our kind of town."},
	{Name: "Chicken Pox", Description: "Infectious disease usually contracted in childhood. Just don't scratch 'em!"},
	{Name: "Chickens", Description: "From incubator to rotisserie in 56 days! Run, chicken, run!"},
	{Name: "Chimpanzees", Description: "Sure, they're related to us; but they don't write, and they NEVER call!"},
	{Name: "China", Description: "The most populous country in the world. More than one-fifth of the world's total population lives within its borders."},
	{Name: "Chinatown", Description: "International travel, just around the corner."},
	{Name: "Choir Boys", Description: "They sound angelic, but ..."},
	{Name: "Chorus Girls", Description: "Long legs and high kicks!"},
	{Name: "Cigarette Burns", Description: "Another reason to give up smoking."},
	{Name: "Cigarettes", Description: "Mind if I smoke?"},
	{Name: "Cinco de Mayo", Description: "Marks the victory of the Mexican Army over the French at the Battle of Puebla, in 1862."},
	{Name: "Cindy Crawford", Description: "1966- , American Supermodel. What dreams are made of."},
	{Name: "Clark Gable", Description: "1901-60, American film actor, noted as a romantic lead. Frankly, my dear, he didn't give a damn."},
	{Name: "Claude Monet", Description: "1840-1926, French painter, regarded as one of the leaders on the impressionist movement."},
	{Name: "Cleaning The Bathroom", Description: "It's YOUR turn!"},
	{Name: "Cleopatra", Description: "c. 69-30 BC, Queen of Egypt, noted for love affairs with Julius Caesar and Mark Antony, which came back to bite her in the asp."},
	{Name: "Clint Eastwood", Description: "1930-, American film actor and director, past mayor of Carmel, California. Has earned fistfuls of dollars."},
	{Name: "Clowns", Description: "They would be really funny if they weren't so darn scary."},
	{Name: "Cocaine", Description: "Alkaloid obtained from leaves of the coca plant and used as a local anesthetic and abused as a drug."},
	{Name: "Cockroaches", Description: "Annoying insects that can survive a nuclear war. Fortunately, they can't survive the heel of your shoe."},
	{Name: "Coconuts", Description: "\"Put the lime in the coconut, and drank them both up.\" -Harry Nillson"},
	{Name: "Cold Pizza", Description: "The breakfast of champions."},
	{Name: "Communists", Description: "\"From each, according to their ability, to each according to their need.\" I need a new Ferrari."},
	{Name: "Commuting", Description: "The daily grind. And we're not talking coffee."},
	{Name: "Computer Hackers", Description: "We didn't mean to shut down the entire government ..."},
	{Name: "Computers", Description: "British mathematician Charles Babbage worked out the principles of the modern digital computer in the late 1800s."},
	{Name: "Confucius", Description: "c. 551-479 BC, K'ung Fu-Tzu, Chinese philosopher and one of the most influential figures in Chinese history."},
	{Name: "Conspiracy Theories", Description: "Oh, that was just a coincidence!"},
	{Name: "Construction Workers", Description: "Hard hats -hard bodies."},
	{Name: "Corn On The Cob", Description: "A grain native to the Americas, corn was a staple food for many centuries before corn holders were invented."},
	{Name: "Corvettes", Description: "In 1953, Chevrolet introduced the Corverre, the first mass-produced sports car with a fiberglass body. The perfect cure for a midlife crisis."},
	{Name: "Count Dracula", Description: "\"I vant to suck your blood!\""},
	{Name: "Country Music", Description: "Encompassing styles such as western swing, honky-tonk, bluegrass and rockabilly. Should mention a pickup truck and a dog named \"Bo.\""},
	{Name: "Cow-Pies", Description: "When dried, these \"cow chips\" are hurled discus-like over great distances. It's true."},
	{Name: "Crazy Horse", Description: "1849?-77, chief of the Oglala Sioux. A leader in the Native American resistance to the westward expansion on the United States."},
	{Name: "Creamed Corn", Description: "Eat it, it's good for you."},
	{Name: "Crystal Balls", Description: "I see a Green Apple card in your future."},
	{Name: "Cuba", Description: "Island republic in the Caribbean, just south of Florida. Beans and rice never tasted so good."},
	{Name: "Cults", Description: "They seemed nice ..."},
	{Name: "Custer's Last Stand", Description: "1866, Little Big Horn. Very big mistake."},
	{Name: "Dandruff", Description: "Dry skin on your scalp? Sounds a bit flaky."},
	{Name: "Danielle Steel", Description: "1947- , Prolific romance novelist. \"Suddenly, Stephanie spotted Lance on the beach ...\""},
	{Name: "Danny DeVito", Description: "1944- , American television, motion-picture actor, and director. Star of Taxi, Romancing The Stone, Twins, and Get Shorty."},
	{Name: "Dark Alleys", Description: "Don't go there!"},
	{Name: "Darth Vader", Description: "\"Luke ... (wheeze) .. I am ... (wheeze) ... your father ... and you don't write, you don't call ... NOTHING.\""},
	{Name: "Dating", Description: "First stage of the human mating ritual."},
	{Name: "David Letterman", Description: "1947- , American television entertainer and talk-show host. And ... the Number One reason to watch him (drum roll, please): TOP TEN LISTS!"},
	{Name: "Daytime TV", Description: "Soap operas, game shows, talk shows and reruns ... is this a great country or what?"},
	{Name: "Death Valley", Description: "Arid, desolate and hellish region of California. Named by a survivor of an attempted 1849 crossing."},
	{Name: "Deer Hunting", Description: "Nooo! Nooooo! Not BAMBI'S MOTHER!"},
	{Name: "Demi Moore", Description: "1962-, American actor in St. Elmo's Fire, Ghost and GI Jane."},
	{Name: "Democrats", Description: "Their symbol is the donkey, or ass. Insert your own joke here."},
	{Name: "Denzel Washington", Description: "1954- , American actor known for his powerful roles in such movies as Cry Freedom, Malcolm X, and Mississippi Masala."},
	{Name: "Detroit", Description: "The Motor City is the world's foremost automobile manufacturing center, and the tenth largest city in the U.S."},
	{Name: "Diamonds", Description: "The hard fact: they are just highly refractive crystalline allotropes."},
	{Name: "Discos", Description: "Where you go to catch \"Saturday Night Fever.\""},
	{Name: "Discovering America", Description: "1492, Christopher Columbus discovered that America was discovered centuries before he arrived."},
	{Name: "Disneyland", Description: "You've just won the \"Apples to Apples(R) Grand Masters Tournament.\" Where're you gonna go?"},
	{Name: "Divorce", Description: "It's a trial separation that goes to trial."},
	{Name: "Doctors", Description: "Over twenty years of education and they're still \"practicing\" medicine?"},
	{Name: "Doing The Dishes", Description: "You wash, I'll watch."},
	{Name: "Dolly Parton", Description: "1967- , American singer, songwriter, and actor. Known as much for her personal style as for her successful career."},
	{Name: "Dr. Kevorkin", Description: "1928- , Controversial advocate of doctor-assisted suicide."},
	{Name: "Dr. Seuss", Description: "1904-1991, Theodor Suess Geisel , the cat who came up with \"The Cat in the Hat.\""},
	{Name: "Driving Off A Cliff", Description: "It was either that or hire someone to do my takes."},
	{Name: "Duct Tape", Description: "All-purpose, ... all the time ..."},
	{Name: "E-Mail", Description: "You've got JUNK mail!"},
	{Name: "Ear Wax", Description: "A waxy, yellowish substance that protects the ear from dust, bacteria, and from hearing things you don't want to hear."},
	{Name: "Earthquakes", Description: "The Richter scale is named after the American seismologist Charles Richter. Did the earth move for you?"},
	{Name: "Earwigs", Description: "Nocturnal insects with abdominal pincers. Nothing to do with ears or wigs."},
	{Name: "East Coast", Description: "From New England to Florida. They're not like folks 'round here ..."},
	{Name: "Eddie Murphy", Description: "1961-, American comedian, actor, and producer. Best known for his work in 48 Hours, Beverly Hills Cop and on Saturday Night Live."},
	{Name: "Eleanor Roosevelt", Description: "1884-1962, first lady, social activist, author, lecturer, and U.S. representative to the United Nations."},
	{Name: "Electric Eels", Description: "Slippery and slimy snakelike fishes that emit electrical charges. The shocking truth!"},
	{Name: "Electricity", Description: "The repulsive or attractive force between two stationary bodies. No problem unless one of those bodies is yours."},
	{Name: "Elephants", Description: "The largest living land mammal, with two species: Indian and African. Not counting Dumbo, there are no American elephants."},
	{Name: "Elizabeth Taylor", Description: "1932- , American actor, noted for her lush beauty, emotional performances and multiple husbands."},
	{Name: "Elvis Presley", Description: "1935-77, American singer and actor and the king of rock-and-roll. His death left the music world all shook up."},
	{Name: "Emily Dickinson", Description: "1830-86, American poet, whose lyrics are psychologically astute treatments of love, death, and immortality. So there."},
	{Name: "Ernest Hemingway", Description: "1899-1961, American novelist and short-story writer, whose macho style is crisp, laconic and understated."},
	{Name: "Europe", Description: "The Old Country ... except to people who live there."},
	{Name: "Exorcism", Description: "To ceremoniously expel an evil spirit."},
	{Name: "Eyes", Description: "Light-sensitive organ of vision in animals. See?"},
	{Name: "Falling Down", Description: "\"What we call failure is not the falling down, but the staying down.\" -Mary Pickford"},
	{Name: "Family Reunions", Description: "Just to remind you why you moved away in the first place ..."},
	{Name: "Family Vacations", Description: "Dad? Dad? Are we there yet? Are we there yet? Are we? Huh? Dad?"},
	{Name: "Family Values", Description: "Often said but seldom understood."},
	{Name: "Fast Food", Description: "You want fries with that?"},
	{Name: "Feathers", Description: "Which weighs more, a pound of feathers or a pound of rocks?"},
	{Name: "Feminists", Description: "Political and social activists who support selected women's causes."},
	{Name: "Festering Wounds", Description: "Quit picking at that!"},
	{Name: "Fidel Castro", Description: "1927-, Cuban revolutionary and Communist dictator since 1976. He earned a PhD in law in 1950."},
	{Name: "Firefighters", Description: "Emperor Augustus instituted a corps of fire-fighting \"watchmen\" in 24 B.C. Nero, on the other hand, fiddled while Rome burned."},
	{Name: "Firestorms", Description: "Some severe wildfires require more than 10,000 firefighters. And, wouldn't ya know it, some idiot parked in front of the hydrant!"},
	{Name: "Fireworks", Description: "Includes firecrackers, Roman candles, and bottle rockets. It's all fun until someone loses an eye ... and a nose ... and an arm ..."},
	{Name: "First Man On The Moon", Description: "July 20, 1969. \"That's one small step for a man, one giant leap for mankind.\" -Neil A. Armstrong"},
	{Name: "Flipper", Description: "American television dolphin of the 1960's ... like Lassie, only wetter."},
	{Name: "Fly Fishing", Description: "... if you can\"t catch flies any OTHER way ..."},
	{Name: "Flying Monkeys", Description: "The reason why \"The Wizard Of Oz\" still gives us nightmares."},
	{Name: "Forest Fires", Description: "\"Only YOU can prevent forest fires.\" The heat is on!"},
	{Name: "Fort Knox", Description: "American military post in Kentucky, containing the greater part of the gold reserve of the U.S. government."},
	{Name: "Fourth Of July", Description: "\"Independence Day\" in the United States. \"Thank Goodness We Got Rid of Them Day\" in Britain."},
	{Name: "Frank Lloyd Wright", Description: "1867-1959, pioneering American architect. Considered one of the greatest designers of the 20th century."},
	{Name: "Frank Sinatra", Description: "1915-98, the greatest American pop singer of his generation, award winning film and television actor. Do-be do-be do, baby."},
	{Name: "Freckles", Description: "No matter what they tell you, freckles won't grow together to form a great-looking tan."},
	{Name: "Freedom", Description: "Express yourself!"},
	{Name: "French Wines", Description: "The perfect complement to an overpriced meal."},
	{Name: "Fresh Water Pearls", Description: "String them along ..."},
	{Name: "Friction", Description: "Resistance to the motion of a body in contact with another body ... any body will do."},
	{Name: "Fund Raising", Description: "Hello ... my name is Jonathan, would you like to buy some fruit, magazines, candy bars, wreaths, pizzas ... ?"},
	{Name: "Funerals", Description: "\"He who dies with the most toys is, nonetheless, still dead.\" - Anonymous"},
	{Name: "Fur", Description: "The characteristic covering of mammals and people with money."},
	{Name: "Fuzz", Description: "Lint ... Policemen ... Whatever ..."},
	{Name: "Gall Bladder", Description: "Where excess bile is stored. Stored for what, we don't know."},
	{Name: "Gang Members", Description: "\"When you're a Jet, you're a Jet all the way...\" -West Side Story"},
	{Name: "Garrison Keillor", Description: "1942- , American author and radio star. He shares the Midwest perspective with 2.6 million listeners each week on A Prairie Home Companion."},
	{Name: "Garth Brooks", Description: "1962- , American country music singer and songwriter. He's got friends in low places."},
	{Name: "Geishas", Description: "Japanese women training in traditional singing, dancing, and entertaining. Of course, you would never recognize them without all that make-up."},
	{Name: "Gen. George S. Patton", Description: "1885-1945, the commander of the American Third Army during World War II. -a.k.a. Olf Blood and Guts"},
	{Name: "Genetic Engineering", Description: "What DO you get when you cross a monkey with a potato?"},
	{Name: "George W. Bush", Description: "1946- , 43rd president of the United States. The second time ever that the son of a former president was elected to the office."},
	{Name: "George Washington", Description: "1732-99, First President of the United States. He chopped down a cherry tree to make false teeth, or something like that ..."},
	{Name: "Georgia O'Keeffe", Description: "1887-1986, American abstract painter known for her still life compositions. Her skull paintings prove that beauty is more than skin deep."},
	{Name: "Getting A Hug", Description: "Hmmmm ... nice."},
	{Name: "Ghost Towns", Description: "Population unknown."},
	{Name: "Ghosts", Description: "Nonmaterial embodiments or the essence of organisms (mostly human beings). Quite spirited"},
	{Name: "Giant Squid", Description: "Going fishing for giant squid? Nautilus I have to ..."},
	{Name: "Gila Monsters", Description: "The largest, and only poisonous lizard found in the United States."},
	{Name: "Gingko Trees", Description: "An Asiatic tree, Gingko biloba, known for its fan shaped leaves. We can't remember what it's good for."},
	{Name: "Ginseng", Description: "Common name for plants of the ginseng family, source of a stimulant and a supposed aphrodisiac."},
	{Name: "Girl Scouts", Description: "I'll take six boxes of Thin Mints and three of the ... you know, the kind with the peanut butter."},
	{Name: "Girlfriends", Description: "Girlfriend - let's talk!"},
	{Name: "Giving A Hug", Description: "\"One may give without loving; but none can love without giving.\" -Anonymous"},
	{Name: "Glaciers", Description: "It'll be a cold day when we see THEM again ..."},
	{Name: "Glazed Donuts", Description: "If you're going to be late, take a box of donuts."},
	{Name: "Global Warming", Description: "Is it hot in here, or is it just me?"},
	{Name: "Going To Church", Description: "Weddings, funerals, bazaars, and bingo!"},
	{Name: "Going To Grandma's", Description: "\"Grandmother, what big teeth you have!\" -Little Red Riding Hood"},
	{Name: "Going To School", Description: "Secondary education? It's elementary."},
	{Name: "Going To The Dentist", Description: "This won't hurt a bit ..."},
	{Name: "Going To The Gym", Description: "No pain, no gain."},
	{Name: "Gold Chains", Description: "The more, the better."},
	{Name: "Goldfish", Description: "The pet, the carnival prize, or the snack cracker."},
	{Name: "Golf-Ball-Sized Hail", Description: "... which is almost as impressive as hail-sized golf balls ..."},
	{Name: "Grace Kelly", Description: "1929-82, Princess of Monaco and American film star of Dial M for Murder, Rear Window, and To Catch a Thief. Always chic, always elegant."},
	{Name: "Graffiti", Description: "Art in a can. We\"re drawn to it."},
	{Name: "Grass Skirts", Description: "Hula loves you, baby?"},
	{Name: "Grave Robbers", Description: "Famous for their bodies of work."},
	{Name: "Gravity", Description: "In 1684, the law of gravitation was formulated by English physicist Sir Isaac Newton, who recognized the gravity of the situation."},
	{Name: "Greenpeace", Description: "International organization dedicated to preserving the Earth's natural resources, and its diverse plant and animal life."},
	{Name: "Gym Teachers", Description: "\"I am a Physical Education Teacher. Call me a gym teacher again and you can drop and give me ten!\""},
	{Name: "Hair Transplants", Description: "Oh, it looks so natural ..."},
	{Name: "Hairballs", Description: "Cough it up, kitty ..."},
	{Name: "Halloween", Description: "October 31, the eve of All Saints' Day, celebrated with costumes, treats, and scary stuff. Not just for kids any more!"},
	{Name: "Hand Grenades", Description: "Close only counts in horseshoes and hand grenades!"},
	{Name: "Handcuffs", Description: "\"You have the right to remain silent...\""},
	{Name: "Handguns", Description: "Source of a never-ending controversy as to how to get them out of the hands of the bad guys and into the hands of the good guys."},
	{Name: "Hangnails", Description: "We've fingered the cause of the pain."},
	{Name: "Having A Baby", Description: "\"Rock-a-bye baby, on the tree top ...\" Who would put a kid on a tree top?"},
	{Name: "Having An Operation", Description: "What a cutup! A real stitch."},
	{Name: "Hawaii", Description: "The eight islands that make up America's 50th state entered the Union on August 21, 1959."},
	{Name: "Helen Keller", Description: "1880-1968, American author and lecturer who overcame deafness and blindness with the help of her companion, Anne Sullivan."},
	{Name: "Hiccups", Description: "How do you, hic, get em? How do you, hic, get rid of \"em?"},
	{Name: "High School Football", Description: "The whole ten yards!"},
	{Name: "High School Reunions", Description: "See also: \"root canal, as fun as ...\""},
	{Name: "Hillary Rodham Clinton", Description: "1947- , New York Senator, lawyer, and former American First Lady."},
	{Name: "Hiroshima", Description: "1945 - \"I am become death, the destroyer of worlds\" - J. Robert Oppenheimer, on the detonation of the first atmoic bomb."},
	{Name: "HMOs", Description: "Heath Maintenance Organizations. Here's to your health ..."},
	{Name: "Hockey", Description: "Did you hear about the big fight last night? All of a sudden, a hockey game broke out!"},
	{Name: "Hollywood", Description: "Motion picture and television industry center of the world. Hooray for Hollywood!"},
	{Name: "Homeless Shelters", Description: "In the United States, nearly three-quarters of the help for the homeless comes from the private sector, mostly from church soup kitchens."},
	{Name: "Homer Simpson", Description: "Fictional cartoon character created by Matt Groening. D'oh!"},
	{Name: "Homework", Description: "Something to do during comercials."},
	{Name: "Hooligans", Description: "\"Hey! Kids! Get outta my yard!\""},
	{Name: "Horseback Riding", Description: "WHOAAA!!!"},
	{Name: "Hot Lava", Description: "There's no better way to serve it."},
	{Name: "House Guests", Description: "How many visitors does it take to drive you crazy? Go on -take a guest!"},
	{Name: "Hummingbirds", Description: "Why do hummingbirds hum? Because they don't know the words ... ... da-dum, dum!"},
	{Name: "Humphrey Bogart", Description: "1899-1957, American film actor, starred in such classics as The Maltese Falcon and Casablanca. \"Here's looking at you kid.\""},
	{Name: "Icebergs", Description: "May reach 300 to 500 feet above the oceans's surface. Ask the captain of the Titanic about the 90 percent that's UNDER water."},
	{Name: "In A Coma", Description: "A deep, prolonged state of unconsciousness ... sometimes you just feel that way."},
	{Name: "Incense", Description: "Incense is better than no sense at all."},
	{Name: "India", Description: "The world's seventh largest country by area, but the second most populous, with one billion people."},
	{Name: "Indiana Jones", Description: "Fictional archeologist and action hero. Proof that a good hat and a whip can take you a long way."},
	{Name: "Industrial Revolution", Description: "The first Industrial Revolution occurred in Great Britain at the end of the 1700s. The second came with the invention of the \"Clapper.\""},
	{Name: "Infomercials", Description: "One of these days, one of them may even say something informative."},
	{Name: "Inside The Sun", Description: "Consisting mostly of hydrogen, the temperature reaches almost 16,000,000 K (about 29,000,000 F)."},
	{Name: "Intellectuals", Description: "They think they're so smart."},
	{Name: "Ireland", Description: "Island of the British Isles, west of Great Britain. Known for its distinctive traditional dance and music."},
	{Name: "Israel", Description: "Located on the Mediterranean, the state of Israel was reated by a 1948 U.N. mandate."},
	{Name: "Italy", Description: "European Republic, shaped like a boot - a very fashionable boot."},
	{Name: "Jack Nicholson", Description: "1937- , American motion-picture actor of \"Chinatown,\" \"Terms Of Endearment\" and \"The Shining.\" He's as good as it gets!"},
	{Name: "Jack The Ripper", Description: "Accused of murdering six women in 1888, and suspected in other murders. Still at large."},
	{Name: "Jackie Chan", Description: "1954-, actor, director, martial artist. Screen name, Sing Lung, means \"Becoming the Dragon.\" That's \"MISTER Becoming the Dragon\" to you!"},
	{Name: "Jacques Cousteau", Description: "1910-97, French naval officer, marine explorer, and author. Best known as a documentary filmmaker."},
	{Name: "Jamaica", Description: "Third largest island of the Greater Antilles, south of Cuba. Tropical climate, reggae music, and jerk cooking."},
	{Name: "James Bond", Description: "Fictional British secret agent created by English author Ian Fleming. Shaken, but never stirred."},
	{Name: "James Dean", Description: "1931-55, American actor of film, stage, and television. His role in Rebel Without a Cause helped define \"cool.\""},
	{Name: "Japan", Description: "An Asian constitutional monarchy. The capital city is Tokyo. Let's see ... sushi, Godzilla, earthquakes ..."},
	{Name: "Japanese", Description: "How many Japanese does it take to screw in a light bulb? Who needs light bulbs when you've got OUR new technology!"},
	{Name: "Jelly Beans", Description: "Well, as long as we HAVE to eat our vegetables ..."},
	{Name: "Jennifer Lopez", Description: "1970-, American singer and actor of Selena, Money Train, and Maid In Manhattan."},
	{Name: "Jerry Springer", Description: "1944- , controversial talk-show host. Don't those people know that millions of us are watching?"},
	{Name: "Jesse Jackson", Description: "1941-, American civil rights leader. Named to \"The Gallup List of Ten Most Respected by Americans\" for ten years."},
	{Name: "Jesse Ventura", Description: "1951-, wrestler, Navy Seal, and former governor of Minnesota. Author of I Ain't Got Time To Bleed."},
	{Name: "Jim Carrey", Description: "1962- , Canadian comedian and actor. Famous for outrageous faces, and dumb and dumber characters."},
	{Name: "Jimmy Stewart", Description: "1908-97, America's favorite self-image. Mr. Smith Goes to Washington, Rear Window, Vertigo, and It's a Wonderful Life, ... and it probably was."},
	{Name: "Joan Of Arc", Description: "1412-31, patron saint of France who decisively turned the tide of the Hundred Years' War, which really burned her up."},
	{Name: "Jodie Foster", Description: "1962- , American actor began her career on Mayberry, R.F.D. and went on to win Academy Awards for The Accused and Silence Of The Lambs."},
	{Name: "John F. Kennedy", Description: "1917-63, 35th president of the US. \"Ask not what your country can do for you; ask what you can do for your country.\""},
	{Name: "John Glenn", Description: "1921- , The first U.S. astronaut to orbit the earth in 1962, and a U.S. Senator. Never too old to shoot for the moon!"},
	{Name: "John Philip Sousa", Description: "1854-1932, American bandmaster and composer of Stars and Stripes Forever. Known as \"The March King.\""},
	{Name: "John Travolta", Description: "1954 - , American actor of \"Welcome Back, Kotter,\" \"Grease,\" \"Saturday Night Fever\" and \"Pulp Fiction.\" That man can dance!"},
	{Name: "Judge Judy", Description: "Ms. Sheindlin presides over real-life cases on this TV courtroom show. \"I'm the boss, applesauce!\""},
	{Name: "Julia Roberts", Description: "1967-, American actor and Pretty Woman. Also starred in Steel Magnolias, My Best Friend's Wedding, and Erin Brockovich."},
	{Name: "Junk Mail", Description: "Contests, credit card applications, solicitations and political ads."},
	{Name: "Jupiter", Description: "Story Problem: If one year on Jupiter equals 11.86 Earth years, and one day equals 9.92 Earth hours, how many Earth hours are there in a Jupiter year?"},
	{Name: "Katherine Hepburn", Description: "1909-2003, American actor and winner of four Academy Awards. She starred in such classics as The African Queen."},
	{Name: "Keanu Reeves", Description: "1964- , American actor of Bill And Ted's Excellent Adventure, The Matrix and Speed. Keanu means \"cool breeze over the mountains.\""},
	{Name: "Killer Whales", Description: "Black and white predatory whales. Boy, can they sing!"},
	{Name: "Kilts", Description: "If Mel Gibson can wear one, so can you."},
	{Name: "King Arthur", Description: "Legendary British king best known for Camelot and round tables."},
	{Name: "King Henry VIII", Description: "1491-1547, King of England, and founder of the Church of England. Six wives, no waiting."},
	{Name: "Knock-Knock Jokes", Description: "Who's there?"},
	{Name: "Labor Unions", Description: "Look for the Union label. And, while you're at it, look for Jimmy Hoffa ..."},
	{Name: "Large Mouth Bass", Description: "Oh, please, let it not sing ..."},
	{Name: "Las Vegas", Description: "The first casino opened in Las Vegas in 1946. Las Vegas ... or it that Lost Wages?\""},
	{Name: "Lawyers", Description: "We'd throw some joke in here, but we're afraid of getting sued."},
	{Name: "Leaf Blowers", Description: "Toro, Toro, Toro!"},
	{Name: "Leather", Description: "Animal hide. Leather you like it or not."},
	{Name: "Leeches", Description: "Any mention of lawyers, agents, or reporters would be FAR too easy ..."},
	{Name: "Lemons", Description: "When life gives you lemons, make lemonade ... or, in the case of a car, take it back. There's a law, you know!"},
	{Name: "Lenin's Tomb", Description: "We'd love to visit Lenin's Tomb, but it's probably just another communist plot."},
	{Name: "Leonardo Da Vinci", Description: "1452-1519, Florentine artist, sculptor, architect, engineer, scientist, and all-around smartypants."},
	{Name: "Lightning", Description: "Electrical discharge between rain clouds, or between a rain cloud and the earth, or between a rain cloud and an idiot with a kite."},
	{Name: "Loan Sharks", Description: "As dangerous as \"Jaws\", but without the charisma."},
	{Name: "Lobster", Description: "Crustaceans closely related to freshwater crayfishes. Market price."},
	{Name: "Local Police", Description: "They know who you are and they know where you live."},
	{Name: "Log Cabins", Description: "Among the many Americans born in log cabins were Preisdents Harrison, Lincoln, and Grant. Just pass the maple syrup."},
	{Name: "Lollipops", Description: "Sucker!"},
	{Name: "London", Description: "Founded even before the Romans reached England's shores, now the capital of Great Britain."},
	{Name: "Looking For A Job", Description: "Will work for fool ..."},
	{Name: "Los Angeles", Description: "LA LA Land."},
	{Name: "Losing Your Job", Description: "They just didn't understand me!"},
	{Name: "Lucille Ball", Description: "1911-89, American actor and comedian. You love Lucy? I love Lucy."},
	{Name: "Machine Guns", Description: "Automatic, rapid-fire, repeating weapons. The Gatling gun was used as early as the American Civil War."},
	{Name: "Mad Cow Disease", Description: "Degenerative brain disorder in cattle. The reason they don't know enough to come in out of the rain?"},
	{Name: "Madame Curie", Description: "1867-1934, French chemist and physicist who won a Nobel Prize for her work on radiation. Fun fact: A \"curie\" is a unit of radioactivity."},
	{Name: "Madonna", Description: "1958-, American singer, songwriter, actor, writer, and 1980s pop icon. Blond Ambition."},
	{Name: "Magic Tricks", Description: "\"Nothin' up my sleeve ...\" - Bullwinkle"},
	{Name: "Mahatma Gandhi", Description: "1869-1948, Indian leader and philosopher who preached nonviolence. Was assassinated for his efforts."},
	{Name: "Manhattan", Description: "I'll take Manhattan!."},
	{Name: "Mardi Gras", Description: "Fat Tuesday marks the final day before the Christian fast of Lent, a 40-day period of self-denial and abstinence. SO LET'S PARTY!"},
	{Name: "Marilyn Monroe", Description: "1926-62, American movie star, pinup and sex symbol. Just ask the Kennedys."},
	{Name: "Mark Twain", Description: "1835-1910, American writer and humorist, best known for the adventures of Tom Sawyer and Huckleberry Finn."},
	{Name: "Marriage", Description: "If love and marriage go together like a horse and carriage ... who's the horse?"},
	{Name: "Mars", Description: "The fourth planet from the sun. Where men come from."},
	{Name: "Martha Stewart", Description: "1941-, television personality, magazine editor, and author. Domestic arts are her stock-in-trade."},
	{Name: "Martin Luther King, Jr.", Description: "1929-68, American civil rights leader and advocate of nonviolent resistance. Was assassinated for his efforts."},
	{Name: "Meat Cleavers", Description: "No relation to Ward, June, or the Beaver ..."},
	{Name: "Meatloaf", Description: "Large and intimidating -the dish not the singer!"},
	{Name: "Meg Ryan", Description: "1961- , American actor and girl-next-door star of When Harry Met Sally, Sleepless In Seattle, and You've Got Mail."},
	{Name: "Mel Gibson", Description: "1956-, Australian actor. Known for The Road Warrior, Braveheart and :eatha; Weapon I, II, III, IV ..."},
	{Name: "Men", Description: "REAL Men."},
	{Name: "Men In Black", Description: "We're not here. You don't see us. The government did NOT send us."},
	{Name: "Meryl Streep", Description: "1959-, accomplished American actor, two-time Oscar winner, with over a dozen Academy Award nominations."},
	{Name: "Mexico", Description: "Federal republic in North America. The capital and largest city is Mexico City."},
	{Name: "Mice", Description: "\"The best-laid schemes o' mice an' men ...\" -Robert Burns"},
	{Name: "Michael Jackson", Description: "1958-, American popular singer, dancer, and songwriter. Welcome to Neverland."},
	{Name: "Michael Jordon", Description: "1963- , American professional basketball legend, led Chicago to six world championships. No bull."},
	{Name: "Michelangelo", Description: "1475-1564, inspired Italian sculptor, architect, painter, and poet. A REAL Renaissance man."},
	{Name: "Michelle Pfeiffer", Description: "1957-, American actor whose career began with Grease 2. She'd like us to forget that but remember her Oscar nominations."},
	{Name: "Microsoft", Description: "A leading American software company. We'd say more but we don't want to monopolize your time ..."},
	{Name: "Midlife Crisis", Description: "\"Here comes your 19th nervous breakdown ...\" -The Rolling Stone"},
	{Name: "Mike Tyson", Description: "1966- , American heavyweight boxer. Lend him your ear ..."},
	{Name: "Miles Davis", Description: "1926-91, innovative, influential, and respected American jazz trumpter player and band layer."},
	{Name: "Milk", Description: "Three glasses a day will give you ... the gratitude of the dairy industry."},
	{Name: "Milk Duds", Description: "Chocolate and caramel candy balls. Tooth extractions at no extra charge!"},
	{Name: "Mirrors", Description: "And now, a moment for reflection."},
	{Name: "Mold", Description: "Fuzzy growth produced on organic matter by several types of fungi. Particularly attracted to students' refrigerators"},
	{Name: "Money", Description: "\"The best things in life are free/ But you can give them to the birds and bees/ Just give me money ...\" -Bradford and Gordy"},
	{Name: "Morticians", Description: "Why do you hang around with THOSE stiffs ...?"},
	{Name: "Mosquitoes", Description: "They suck."},
	{Name: "Motorcycles", Description: "The air in your hair and bugs in your teeth."},
	{Name: "Mount Rushmore", Description: "Memorial carved into the side of the Black Hills in South Dakota. Heads above all other monuments."},
	{Name: "MTV", Description: "\"Video killed the radio star.\" -The Buggles"},
	{Name: "Mud", Description: "Water. Dirt. You do the math."},
	{Name: "Mudslides", Description: "Chocolate drink or natural disaster ... both occur frequently in California."},
	{Name: "Muhammad Ali", Description: "1942- , American heavyweight boxing champion. \"Floats like a butterfly, stings like a bee.\""},
	{Name: "Musicals", Description: "South Pacific, The King and I, The Sound of Music, A Chorus Line, Cats, Rent ..."},
	{Name: "My 16th Birthday", Description: "Dad, can I have the keys to the car, please?"},
	{Name: "My Bank Account", Description: "Speaking of theoretical mathematics and unreal numbers ..."},
	{Name: "My Bathroom", Description: "\"The bathroom was drenched with their splashings\" -Aldous Huxley"},
	{Name: "My Bedroom", Description: "\"No one knows what goes on behind closed doors.\" -Charlie Rich"},
	{Name: "My Body", Description: "Mine is a temple. Specifically, the Temple of Doom ..."},
	{Name: "My Boss", Description: "... is an idiot. You know it; we know it."},
	{Name: "My Dreams", Description: "\"What dreams may come ...\" -Shakespeare's Hamlet"},
	{Name: "My Family", Description: "They'll drive you nuts. As long as you do the same to them, it's all even."},
	{Name: "My First Kiss", Description: "Sparks were flying. Of course, that could have been the braces ..."},
	{Name: "My Friends", Description: "With friends like there, who needs enemies?"},
	{Name: "My Future", Description: "\"The future's so bright, I gotta wear shades ...\" -Timbuk-3"},
	{Name: "My Hair", Description: "Hair today, gone tomorrow ..."},
	{Name: "My High School Prom", Description: "As if adolescence isn't awkward and painful enough ..."},
	{Name: "My Job", Description: "Love it or leave it."},
	{Name: "My Love Life", Description: "\"All you need is love ...\" -The Beatles"},
	{Name: "My Mind", Description: "It's a terrible thing to waste."},
	{Name: "My Neighborhood", Description: "\"Please, won't you be my neighbor?\" -Fred Rogers"},
	{Name: "My Past", Description: "What's past is past ... unless you're a politician ..."},
	{Name: "My Personality", Description: "\"I'm good enough, smart enough and, gosh darn it, people like me.\" -Stewart Smalley played by Al Franken"},
	{Name: "My Refrigerator", Description: "It's a science experiment!"},
	{Name: "Napoleon Bonaparte", Description: "1769-1821, Emperor of France. Met his Waterloo at the Battle of Waterloo. The name should have tipped him off ..."},
	{Name: "NASCAR", Description: "Stock car racing began after World War II, breaking records for speed and for the number of advertisements on a single jacket."},
	{Name: "Neil Simon", Description: "1927-, American producer, playwright, and screenwriter of The Odd Couple, Biloxi Blues, The Sunshine Boys, California Suite, and many more."},
	{Name: "New Orleans", Description: "The Big Easy."},
	{Name: "New Shoes", Description: "Make you feel like dancing ..."},
	{Name: "New York City", Description: "America's most populous city. So good, they named it twice."},
	{Name: "Niagara Falls", Description: "Niagara Falls was formed about 12,000 years ago, when glaciers retreated north, and honeymooners approached from the south."},
	{Name: "Nicholas Cage", Description: "1964- , American actor known for his edgy characters in Leaving Los Vegas, Raising Arizona, and Moonstruck."},
	{Name: "Ninjas", Description: "Teenage mutant turtles need not apply."},
	{Name: "Nobel Peace Prize", Description: "Established by Alfred Nobel. Swedish industrialist and inventor of dynamite. Led to an explosion of peace efforts."},
	{Name: "Noisy Neighbors", Description: "WHAT? I CAN'T HEAR YOU!"},
	{Name: "Normal Rockwell", Description: "1894-1978, American painter, illustrator and all-around interpreter of small town American life."},
	{Name: "Nuclear Power Plants", Description: "\"You've turned a potential Chernobyl into a mere Three Mile Island.\" -Montgomery Burns, \"The Simpsons\""},
	{Name: "NYPD", Description: "The New York Police Department. They're so good, they have their own TV show."},
	{Name: "Oil Spills", Description: "The American oil tanker, Exxon Valdez, went aground in Prince William Sound, Alaska, Mar. 24, 1989. Slick Move."},
	{Name: "Olive Oil", Description: "Derived from fresh ripe fruit, which contain about 20% oil. Better than \"olive\" the other oils."},
	{Name: "On-Line Shopping", Description: "Enter your credit card number now. This is a secure site ... Sure it is ..."},
	{Name: "Oprah Winfrey", Description: "1954- , Television talk show host, actor and all-around American success story."},
	{Name: "Oral Surgery", Description: "You said a mouthful."},
	{Name: "Oranges", Description: "Face it ... nothing rhymes with orange."},
	{Name: "Oxygen", Description: "Oxygen was discovered in 1774. You'd think someone would have noticed it earlier."},
	{Name: "Pablo Picasso", Description: "1881-1973, Spanish painter and sculptor, one of the greatest artists of the 20th century. If only he could draw eyes ..."},
	{Name: "Parenting", Description: "The process of discovering you are becoming just like YOUR parents."},
	{Name: "Paris, France", Description: "The governmental, cultural and gastronomic capital of France. Or the world. Just ask the French."},
	{Name: "Paying Bills", Description: "Also known as \"Debt Restructuring.\""},
	{Name: "Paying Taxes", Description: "Death or Taxes? Do we have to choose right away?"},
	{Name: "Penguins", Description: "Flightless, aquatic birds that reside in the Southern Hemisphere. All dressed up and no place to go."},
	{Name: "Picking Your Nose", Description: "Noses run in our family."},
	{Name: "Pigeons", Description: "Birds with small heads, short necks, stout bodies, and an incredible attraction to statues."},
	{Name: "Pigs", Description: "Domesticated mammal of the swine family. Thaaa ... thaaa ... that's all, folks!"},
	{Name: "Piranha", Description: "Carnivorous fish found in rivers of South America. When you feel like a bite ..."},
	{Name: "Pirates", Description: "\"Yo, ho, yo, ho, a pirate's life for me ...\" - Pirates of the Caribbean"},
	{Name: "Pit Bulls", Description: "Any of several crossbreeds of bulldogs with terriers. Or, several radio hosts we could mention."},
	{Name: "Plane Crashes", Description: "Statistically safer than driving ... unless you crash."},
	{Name: "Plastic", Description: "Giant molecules of organic polymeric materials. Bags and bags of the stuff."},
	{Name: "Playing Chess", Description: "Has tantalized many of the world's greatest minds for almost 14 centuries. It just confuses the rest of us."},
	{Name: "Poison Ivy", Description: "Itching for a walk in the woods?"},
	{Name: "Pokemon", Description: "Cute cartoon monsters you gotta catch. What you do with them is up to you ..."},
	{Name: "Pond Scum", Description: "Simple organisms that carry out photosynthesis ... or spammers."},
	{Name: "Poodles", Description: "The only breed that is better groomed than their owners."},
	{Name: "Popcorn", Description: "Air poppers are for air heads ... I say bring on the butter!"},
	{Name: "Porsche Boxster", Description: "A two-seat, six cylander roadster - elegant design and superior drivability."},
	{Name: "Postal Workers", Description: "\"Neither snow, nor rain, nor heat, nor gloom of night, stays these couriers from the swift completion of their appointed rounds.\""},
	{Name: "Power Tools", Description: "\"More power! More power! Argh! Argh!\" -Tim, the Tool Man, Taylor, \"Home Improvement\""},
	{Name: "Prince Charming", Description: "The perfect man ... mythical, of course."},
	{Name: "Princess Di", Description: "1962-97, beloved English Princess who died in an auto crash. \"Good-bye England's Rose ...\" -Elton John"},
	{Name: "Pro Wrestling", Description: "They're just faking it. But then, so are we."},
	{Name: "Psychiatrists", Description: "\"And how do you feel about that?\""},
	{Name: "Psychics", Description: "The Psychic Friends Network went bankrupt in 1997. Perhaps they should have seen it coming ..."},
	{Name: "Public Radio", Description: "\"Good morning . . . . . This morning . . . . . . . . . . . .we have Wolfgang . . . Amadeus Mozart . . . for your listening pleasure . . .\""},
	{Name: "Puff Daddy", Description: "1971- , American rap artist. \"I'll be Missing You\" shot him to stardom; no pun intended."},
	{Name: "Pulling Weeds", Description: "It's either this or chemical warfare."},
	{Name: "Pumping Iron", Description: "When a great weight needs to be lifted."},
	{Name: "Pushups", Description: "Exercises, a type of bra, or the ice cream treat."},
	{Name: "Pyramids", Description: "Built by ancient civilizations, found mainly in Egypt, Guatemala, Honduras, Mexico and Peru. Probably the result of some pyramid scheme."},
	{Name: "Quentin Terantino", Description: "1963- , Groundbreaking American director and actor. Nice movies, but not nearly enough blood."},
	{Name: "Quicksand", Description: "Just don't let it get you down."},
	{Name: "Ragweed", Description: "A weed of the genus Ambrosia. Nothing to sneeze at."},
	{Name: "Rain", Description: "\"When the rain comes, they run and hide their heads; they might as well be dead.\" -The Beatles"},
	{Name: "Rainbows", Description: "\"Someday they'll find it/ The Rainbow Connection/ The lovers, the dreamers and me ...\" -Kermit the Frog"},
	{Name: "Rappers", Description: "PAENTAL ADVISORY EXPLICIT CONTENT Hasn't seemed to hurt sales..."},
	{Name: "Reading A Good Book", Description: "So many books, so little time."},
	{Name: "Recreational Vehicles", Description: "If they're trying to get away from it all, why are they taking it all with them?"},
	{Name: "Recycling", Description: "More than one million tons of aluminum are NOT recycled each year. Where do you throw your cans?"},
	{Name: "Red Raspberries", Description: "Worth a few scratches."},
	{Name: "Rednecks", Description: "\"You might be a redneck if ...\" -Jeff Foxworthy"},
	{Name: "Redwood Forests", Description: "\"From the Redwood Forests to the Gulf Stream Waters/ This land was made for you and me.\" -Woody Guthrie"},
	{Name: "Reggae Music", Description: "This contemporary Caribbean music, originating in Jamaica, remains an influential style of popular music. Ya mon!"},
	{Name: "Regis Philbin", Description: "1934- , American talk and game show host. Who wants to be a millionaire? Regis, apparently."},
	{Name: "Remote Controls", Description: "The world's handiest invention. That is, if you can find it."},
	{Name: "Republicans", Description: "A U.S. political party symbolized by an elephant ... and don't forget it!"},
	{Name: "Richard Nixon", Description: "1913-94, 37th President of the United States and the only president to have resigned from office. At least that's what the tapes say ..."},
	{Name: "Robert DeNiro", Description: "1943- , Pre-eminent American actor who earned Academy Awards for The Godfather II and Raging Bull. \"Are you looking at me?\""},
	{Name: "Road Kill", Description: "Mmmmmm. Them's good eatin'."},
	{Name: "Road Trips", Description: "\"Get Your Kicks on Route 66.\" -Nelson Riddle"},
	{Name: "Robin Williams", Description: "1952- , versatile American comedian and actor. The furriest man in show business."},
	{Name: "Rock And Roll", Description: "It's here to stay!"},
	{Name: "Rock Concert", Description: "If it's too loud - you're too old."},
	{Name: "Rocket Scientists", Description: "Hey! They're not rocket scie ... oh ... never mind."},
	{Name: "Rocky Mountains", Description: "These extend 2,000 miles from northeastern British Columbia to central New Mexico, and keep the Californians away from everyone else ..."},
	{Name: "Rolling The Car", Description: "You'll flip for this one ..."},
	{Name: "Roman Numerals", Description: "There's a I in VII chance you'll know them."},
	{Name: "Romeo And Juliet", Description: "William Shakespeare's best known play, written in 1595. Youthful love and hasty temperaments."},
	{Name: "Root Beer Floats", Description: "Actually, it's the ice cream that floats!"},
	{Name: "Rosa Parks", Description: "1913-, civil rights icon arrested in 1956 for violating U.S. segregation laws by refusing to give up her bus seat to a white passenger."},
	{Name: "Rosie O'Donnell", Description: "1962-, American actor and comedian. She's in a league of her own!"},
	{Name: "Rubber Gloves", Description: "Just in case ..."},
	{Name: "Running A Marathon", Description: "26 miles, 385 yards: the distance run by a Greek soldier from the town of Marathon to Athens in 490 BC."},
	{Name: "Rush Limbaugh", Description: "1951- , conservative talk-radio personality. Claims to host his radio show with half his brain tied behind his back, just to make it fair."},
	{Name: "Russia", Description: "The world's largest country, spanning 11 time zones. Famous for borscht, ballet, chess and vodka -just don't mix them."},
	{Name: "Rust", Description: "\"Rust never sleeps.\" -Neil Young"},
	{Name: "Saddam Hussein", Description: "1937-, dictator of Iraq 1979-2003."},
	{Name: "Sailors", Description: "\"In the Navy, you can sail the seven seas ...\" -The Village People"},
	{Name: "Salads", Description: "Lettuce not knock the vegetarians."},
	{Name: "Salsa Dancing", Description: "Popular form of Latin American dance. A little jazz, a little blues, a touch of rock and lots of heat."},
	{Name: "Salvador Dali", Description: "1904-89, Spansih artist best known for his dream imagery and surrealism, including the limp watches in The Persistence Of Memory."},
	{Name: "Samuel L. Jackson", Description: "1948-, powerful American actor of Pulp Fiction, Jackie Brown, and The Negotiator."},
	{Name: "Saturday Cartoons", Description: "Get your blanket, a bowl of cereal and snuggle in for three hours of commercials."},
	{Name: "San Francisco", Description: "California's City by the Bay. Where many hearts are left."},
	{Name: "Saturn", Description: "Sixth planet from the sun, and the second largest in the solar system. Has a nice ring to it, don't you think?"},
	{Name: "Scavenger Hunt", Description: "OK kids, here's your list: a marshmallow, a safety pin, a red rubber band, and a moon rock. Go find 'em!"},
	{Name: "Scene Of The Crime", Description: "It was Colonel Mustard, in the library, with the candlestick."},
	{Name: "Schindler's List", Description: "1993 Steven Spielberg film. Powerful real-life story of a Catholic businessman who eventually saved over 1000 Jews in Nazi Poland."},
	{Name: "Science Fair Projects", Description: "No human subjects, please!"},
	{Name: "Science Fiction", Description: "In a galaxy far, far away ..."},
	{Name: "Screeching", Description: "Please stop."},
	{Name: "Sean Connery", Description: "1930- , Accomplished Scottish actor, although best known as the REAL Bond, JAMES Bond ..."},
	{Name: "Shania Twain", Description: "1965- , Canadian country singer and songwriter. \"Shania\" means \"I'm on my way\" in Ojibwa."},
	{Name: "Sharks", Description: "Many species living today are similar to those from 100 million years ago. Because change is scary."},
	{Name: "Shopping Mall", Description: "Three-quarters of the North American population visit a shopping mall at least once a month."},
	{Name: "Silk", Description: "Produced as a cocoon covering by the silk worm, and used in fine fabrics and textiles."},
	{Name: "Silly Putty", Description: "It's putty in your hands!"},
	{Name: "Skateboarding", Description: "It's just going downhill ... down stairs ... down ramps ..."},
	{Name: "Skiing", Description: "The Super Giant Slalom: Swiss for \"suicide.\""},
	{Name: "Skinheads", Description: "Shaved heads, big boots. Some are Nazis, some are not."},
	{Name: "Skunks", Description: "Black and white striped mammals known for their offensive smelling defensive spray."},
	{Name: "Skydiving", Description: "Parachute canopies are usually made from nylon fabric that lasts for thousands of jumps - whether the skydiver does or not."},
	{Name: "Sleeping Pills", Description: "I remember taking them ... I just ... don't rememmer ... how mamy."},
	{Name: "Slivers", Description: "Also known as splinters. The worst ones are under your fingernails."},
	{Name: "Sloppy Joes", Description: "My favorite recipe -open the can."},
	{Name: "Smithsonian Institution", Description: "Located in Washington, D.C., the largest museum complex in the world. Wouldn't that be a great garage sale?"},
	{Name: "Snakes", Description: "Surprising, snakes move rapidly without legs. Also surprising, they find OTHER snakes attractive."},
	{Name: "Snow", Description: "Transparent ice crystals which form around dust and other small particles. Get my drift?"},
	{Name: "Social Security", Description: "American program designed to provide income and services in the event of retirement, sickness, disability, death or unemployment."},
	{Name: "Socks", Description: "\"Black socks, they never get dirty, the longer you wear them the stronger they get.\" -Bill Harley"},
	{Name: "South Africa", Description: "Two oceans, rugged mountains, traditional villages, game sanctuaries, wineries...forget the past and bring on the tourists."},
	{Name: "South Park", Description: "Highly-rated, highly offensive animated cartoon series. \"Oh my God! We killed Kenny!\""},
	{Name: "Soy Sauce", Description: "A brewed seasoning made from soybeans, wheat, and salt."},
	{Name: "Spam", Description: "Mystery meat, or mystery E-mails ..."},
	{Name: "Speeding Tickets", Description: "\"No, officer, I don't have any idea how fast I was going.\""},
	{Name: "Spiders", Description: "There are more than 34,000 species of spiders. Try not to think about THAT right before bedtime."},
	{Name: "Spike Lee", Description: "1957-, American film maker and Knicks fan. Best known for Do the Right Thing, Malcolm X, and 4 Little Girls."},
	{Name: "Spilled Milk", Description: "Got milk? WHOOPS! Apparently not ..."},
	{Name: "Spit", Description: "Ladies and gentlemen, straight from the Salivary Glands ..."},
	{Name: "Spontaneous Combustion", Description: "The ignition of substances without application of an external heat source. A good plot for \"The X-Files.\""},
	{Name: "Sport Utility Vehicles", Description: "Need new tires?"},
	{Name: "Sports Channels", Description: "Any team, any time."},
	{Name: "Star Fruit", Description: "Looks like plastic, tastes like lemons."},
	{Name: "Starry Night", Description: "A sky bright with stars, a classic Van Gogh painting, and a Don McLean song. Three cards in one!"},
	{Name: "State Fair", Description: "Aw, gee whiz, a blue ribbon for Bessie!"},
	{Name: "Steak And Potatoes", Description: "Hot off the grill!"},
	{Name: "Stephen King", Description: "1947- , American author of horror novels, who's sold more than 100 million copies of his books. Talk about frightening ..."},
	{Name: "Steve Martin", Description: "1945- , American comedian, actor, writer, and \"wild and crazy guy.\""},
	{Name: "Steven Spielberg", Description: "1947-, American movie director and producer, and overachiever. From E.T. to Schindler's List... too many to list."},
	{Name: "Stonehenge", Description: "Prehistoric stone monument located north of Salisbury, England."},
	{Name: "Strawberry Shortcake", Description: "Summertime and the eating is easy ..."},
	{Name: "Stubbed Toes", Description: "It'll feel better when it quits hurting."},
	{Name: "Stunt People", Description: "When you need someone to take the fall."},
	{Name: "Summer Camp", Description: "If the bugs don't get you, the poison ivy will!"},
	{Name: "Sunday Drivers", Description: "Now available ANY day of the week!"},
	{Name: "Superman", Description: "Fictional comic book superhero loved by Lois Lane and Jerry Seinfeld."},
	{Name: "Supermodels", Description: "Long legs = big bucks."},
	{Name: "Surfing The Net", Description: "www.otb-games.com"},
	{Name: "Sushi", Description: "Who would ever have guessed that raw fish could be so fashionable?"},
	{Name: "Swiss Bank Accounts", Description: "Do you think everyone in Switzerland has one?"},
	{Name: "Swiss Chocolate", Description: "\"What use are cartridges in battle? I always carry chocolate instead.\" -George Bernard Shaw"},
	{Name: "Swiss Cheese", Description: "Guess it comes from holey cows ..."},
	{Name: "Taking A Bath", Description: "Bathing facilities have been found in excavations in India from before 2000 BC. Soap-on-a-Rope hasn't."},
	{Name: "Talk Radio", Description: "Talk about air pollution."},
	{Name: "Teachers", Description: "If you can play this game, thank a teacher."},
	{Name: "Telemarketers", Description: "\"No, thank you ... No, I'm not interested ... No, I have to go now ...\""},
	{Name: "Televangelists", Description: "Not to be confused with Teletubbies."},
	{Name: "Television", Description: "One-hundred and sixty-four channels, and nothing worth watching."},
	{Name: "Telling The Truth", Description: "\"There are two kinds of truth. There are real truths and there are made-up truths.\" -Marion Barry, ex-mayor of Washington, D.C."},
	{Name: "Terrorist Attack", Description: "We will never negotiate with terrorists."},
	{Name: "Thanksgiving Day", Description: "The fourth Thursday of November in the U.S.; the second Monday in October in Canada."},
	{Name: "The 1920s", Description: "Pros: the Jazz Age. Cons: Presidents who look like librarians."},
	{Name: "The 1950s", Description: "Pros: Barbies, barbecues, and bikinis. Cons: McCarthy, the Korean War, television."},
	{Name: "The 1960s", Description: "Pros: the Moon Lsnding, the music. Cons: hippies who refuse to believe they're over."},
	{Name: "The 1970s", Description: "Pros ... uh ... pros ... uh ... GIVE US A MINUTE, OKAY?"},
	{Name: "The 1980s", Description: "Pros: meant the end of the 1970s. Cons: '80s nostalgia."},
	{Name: "The 21st Century", Description: "The future is NOW!"},
	{Name: "The Academy Awards", Description: "The statue known as \"Oscar\" weighs only eight and a half pounds. So why does it carry so much weight?"},
	{Name: "The Beach", Description: "A day at the beach is no day at the beach, ya know?"},
	{Name: "The Beatles", Description: "1960s British band. Only the most revolutionary, influential and universally acclaimed group of the 20th century. That's all."},
	{Name: "The CIA", Description: "The Central Intelligence Agency is responsible for keeping the U.S. government informed of foreign actions affecting the nation's interest."},
	{Name: "The Cold War", Description: "The post-World War II struggle between the US and its allies, and the former USSR and its allies. Things could have gotten hot."},
	{Name: "The Common Loon", Description: "A spotted, red-eyed diving bird -or various friends or family."},
	{Name: "The Dallas Cowboys", Description: "National Football League team known for their cheerleaders and their performance, both on and off the field."},
	{Name: "The Dump", Description: "Just remember to recycle."},
	{Name: "The Eiffel Tower", Description: "Designed and built by French engineer Alexandre Gustave Eiffel for the Paris World's Fair of 1889."},
	{Name: "The Electric Chair", Description: "In U.S. prisons, an alternating current of about 2000 volts is used for electrocution."},
	{Name: "The End Of The World", Description: "\"It's the end of the world as we know it, and I feel fine ...\" -REM"},
	{Name: "The Everglades", Description: "A vast marsh covering much of southern Florida. Watch out for alligators!"},
	{Name: "The Far Left", Description: "They get high Marx from some."},
	{Name: "The Far Right", Description: "Far right for some and far wrong for others."},
	{Name: "The FBI", Description: "The Federal Bureau of Investigation: the investigative agency for the U.S. Department of Justice. They're listening ..."},
	{Name: "The First Day Of School", Description: "\"Fear has many eyes.\" -Cervantes"},
	{Name: "The French Riviera", Description: "Holiday home of the rich, the famous, and the half-naked."},
	{Name: "The Godfather", Description: "The 1972 critically acclaimed Mafia movie that made us as offer we couldn't refuse."},
	{Name: "The Grand Canyon", Description: "217 miles long, 4 to 18 miles wide, and more than 1 mile deep. Now THAT'S grand."},
	{Name: "The Grateful Dead", Description: "American rock band, founded in 1965 and best known for their \"Dead Head\" fans."},
	{Name: "The Great Chicago Fire", Description: "The noteworthy fire of 1871 ... a hot time in the old town ..."},
	{Name: "The Great Depression", Description: "Prozac was invented six decades too late."},
	{Name: "The Green Bay Packers", Description: "Twelve time National Football League world champions, beloved by \"Cheeseheads\" everywhere. Are those brats done yet?"},
	{Name: "The Gulf War", Description: "January - February, 1991. This six week conflict with Iraq was also known as \"Desert Storm.\""},
	{Name: "The Indy 500", Description: "Contestants must drive the full 500 miles. Bathroom breaks ARE allowed."},
	{Name: "The Internet", Description: "Computer-based worldwide information network, and global shopping market."},
	{Name: "The IRS", Description: "The Internal Revenue Service: agency of the U.S. Department of the Treasury responsible for collecting taxes. A human audity."},
	{Name: "The JFK Assassination", Description: "November 22, 1963. The funeral of President Kennedy was watched on television by millions around the world."},
	{Name: "The KKK", Description: "If they're supposed to be the master race, why do they keep misspelling \"Clan\"?"},
	{Name: "The Land Of Oz", Description: "\"I've a feeling we're not in Kansas anymore, Toto.\" -Dorothy, \"The Wizard Of Oz\""},
	{Name: "The Little Mermaid", Description: "The 1837 story by Hans Christian Anderson or the 1989 animated film by Disney. Guess which made more money?"},
	{Name: "The Mafia", Description: "A loose association of criminal groups, bound by a blood oath and sworn to secrecy. Of course, now we have to kill you."},
	{Name: "The Marx Brothers", Description: "Chico, Groucho, Harpo, amd sometimes Zeppo. Their 1930s films include Duck Soup and Animal Crackers."},
	{Name: "The Metric System", Description: "No, thank you. We like our inches and feet!"},
	{Name: "The Midwest", Description: "America's central plains states. They're not like folks 'round here ..."},
	{Name: "The Milky Way", Description: "The galaxy that includes the sun, its solar system, and a chewy layer of caramel."},
	{Name: "The Mississippi River", Description: "The Algonquin words \"Misi sipi\" mean \"big river.\" What's Algonquin for \"muddy\"?"},
	{Name: "The National Enquirer", Description: "American tabloid newspaper. Inquiring minds want to know ... Why the heck does this thing sell?"},
	{Name: "The New York Yankees", Description: "Legendary American baseball team. With so much success, it's obvious why they're reviled."},
	{Name: "The NRA", Description: "National Rifle Association. They're gunning for your vote."},
	{Name: "The Ocean", Description: "How deep is the ocean? 12,000 feet. If they'd known that, maybe they wouldn't have written that stupid song."},
	{Name: "The Old Man And The Sea", Description: "Ernest Hemingway's classic novel - fishing, hunger, fishing, torment, fishing, personal loss ... fishing ..."},
	{Name: "The Olympics", Description: "An international athletic competition held every four years. The thrill of victors and the agony of defeat."},
	{Name: "The Opera", Description: "It ain't over 'til the fat lady sings. Unfortunately, sometimes, not even then."},
	{Name: "The Ozone Layer", Description: "Short for ozonosphere. Theories about the ozone layer are full of holes."},
	{Name: "The Pentagon", Description: "The five-sided home of the U.S. Department of Defense."},
	{Name: "The Pyramids", Description: "The Egyptian pyramids were built from about 2700 BC to about 1000 BC. Tut, tut, tut ..."},
	{Name: "The Renaissance", Description: "Beginning in the 1300s, started in Italy and spread across Europe. Kind of like Espresso bars ..."},
	{Name: "The Rolling Stones", Description: "British \"bad boy\" rock band formed in 1962. Still touring?"},
	{Name: "The San Andreas Fault", Description: "Geological feature in California stretching 600 miles. Like the state doesn't have enough faults already."},
	{Name: "The South", Description: "Dixie: South of the Mason-Dixon line, that is. They're not like folks 'round here ..."},
	{Name: "The Statue Of Liberty", Description: "\"Give me your tired, your poor/ Your huddled masses yearning to breathe free ...\" -Emma Lazarus"},
	{Name: "The Super Bowl", Description: "Who needs another national holiday?"},
	{Name: "The Supreme Court", Description: "The highest court in the United States. Robes, but no wigs."},
	{Name: "The Three Tenors", Description: "Opera stars Placido Domingo, Jose Carreras, and Luciano Pavarotti began recording as The Three Tenors in 1990."},
	{Name: "The Titanic", Description: "It sank in 1912. Get over it!"},
	{Name: "The Universe", Description: "Everything. The big \"It.\" Huge. Massive. THAT big."},
	{Name: "The Vatican", Description: "The Papal State in the middle of Rome. Home of the Pope, Swiss Guards, and lots of pigeons."},
	{Name: "The Vietnam Memorial", Description: "\"The Wall,\" built in 1982, was designed by 21-year-old architecture student, Maya Lin."},
	{Name: "The Williams Sisters", Description: "Venus, 1980-, and Serena, 1981-, Williams, American tennis champs. One heck of a sister act."},
	{Name: "The Wright Brothers", Description: "In 1903, Wilbur and Orville made the first powered airplane flights in history. Although there were delays at the airport."},
	{Name: "The YMCA", Description: "The Young Men's Christian Association has 30 million members in 110 countries. \"It's fun to stay at the Y-M-C-A.\" -The Village People"},
	{Name: "Thomas Edison", Description: "1847-1931, American inventor, developed a light bulb, generator, sound-recorder, and motion picture projector. Show off."},
	{Name: "Thunder", Description: "\"Here it comes again, Thunder and Lightning...\" -ELO."},
	{Name: "Tibet", Description: "Mountainous region of China and religious enclave for a form of Buddhism called Lamaism. Known as the roof of the world."},
	{Name: "Ticks", Description: "All ticks are bloodsucking parasites, but not all bloodsucking parasites are ticks."},
	{Name: "Tidal Waves", Description: "The gigantic ocean waves that strike with tremendous force, and cause considerable damage to life and property. Kind of like Spring Break."},
	{Name: "Tiger Woods", Description: "1975- , American star of the golf circuit. Known for his athletic skill, and youthful, classic style."},
	{Name: "Toasted Marshmallows", Description: "How do you like yours - golden brown or flaming?"},
	{Name: "Toasters", Description: "Wait -don't stick that fork in there!"},
	{Name: "Tobacco Companies", Description: "Who says tobacco's not addictive? THEY can't give it up ..."},
	{Name: "Toes", Description: "\"This little piggy went to market ...\""},
	{Name: "Tom Cruise", Description: "1962-, American actor. It looked like Ricky Business early on, but by 1986 he was Top Gun. No Mission Impossible for him."},
	{Name: "Tom Hanks", Description: "1956-, American actor and star of such varied films as Big, Philadelphia, Forrest Gump, Saving Private Ryan and Castaway."},
	{Name: "Top Of A Rollercoaster", Description: "Just remember: what goes UP ..."},
	{Name: "Tornadoes", Description: "Funnel-shaped cloud whirling destructively at speeds up to 300 mph. \"Honey, do you hear a freight train ... Honey?\""},
	{Name: "Toys", Description: "They're not just for kids, anymore ..."},
	{Name: "Trailer Parks", Description: "Also known as tornado magnets."},
	{Name: "Trampolines", Description: "Trampolines have been used in circuses wince the 18th century. Despite slumps in popularity, they always seem to bounce back!"},
	{Name: "Tree Huggers", Description: "\"Environmentalists\" to the left. \"Wackos\" to the right."},
	{Name: "Truck Stops", Description: "Breakfast 24 hours a day and you're on your way."},
	{Name: "Tyrannosaurus Rex", Description: "Large carnivorous dinosaur of the latter part of the Mesozoic era. My, what big teeth you have!"},
	{Name: "Underwear", Description: "\"Let's keep this brief.\""},
	{Name: "United Nations", Description: "The U.N. was founded in 1945, after World War II ended. Its mission is to maintain world peace. If we ever achieve it, that is ..."},
	{Name: "Vacations", Description: "\"Vacation, all I ever wanted, Vacation, had to get away ...\" -Go-Go's"},
	{Name: "Vampires", Description: "Legendary bloodsucking monsters."},
	{Name: "Victorian England", Description: "An era characterized by moral severity and pompous conservatism."},
	{Name: "Video Games", Description: "Just how DO you get to the thirteenth level of \"Doom\"?"},
	{Name: "Vietnam, 1968", Description: "More than 30,000 Americans had been killed in the Vietnam War by the end of 1968."},
	{Name: "Vincent Van Gogh", Description: "1853-90, Dutch post-impressionist painter known for dramatic sunflowers and self-portraits. Only one of his paintings sold during his lifetime."},
	{Name: "Violins", Description: "It's a pain in the neck, but keep practicing."},
	{Name: "VW Beetles", Description: "The prototype for the original VW Beetle was developed in 1934, and production begin in 1945. Functional, yet so fashionable."},
	{Name: "Waco, Texas", Description: "Texas city near where a 51-day standoff between law-enforcement officials and members of the Branch Davidians occurred in 1993."},
	{Name: "Wall Street", Description: "The financial center of the United States. See also: roller coaster."},
	{Name: "Walt Disney", Description: "1901-1966, the head of some Mickey Mouse company."},
	{Name: "Warts", Description: "Small, benign, circumscribed tumors of the outer layer of the skin. Warts and all!"},
	{Name: "Watching Football", Description: "Sheer athletic prowess by players in peak physical condition is a glorious thing to behold. Pass the chips and beer."},
	{Name: "Water Parks", Description: "You can go down Dead Man's Drop and I'll take the Lazy River."},
	{Name: "Waterbeds", Description: "Could serve as a safety precaution for those who smoke in bed."},
	{Name: "Waterfalls", Description: "\"Don't go chasing waterfalls...\" -TLC"},
	{Name: "Watermelons", Description: "Pardeeville, WI - home of the Watermelon Seed-Spitting & Speed-Eating Championship. The record is 2.5 lbs. of melon eaten in 3.5 seconds."},
	{Name: "Weapons Dealers", Description: "OK, what kind you need? Assault, Automatic, Atomic ...?"},
	{Name: "Weddings", Description: "\"Ding, dong, the bells are gonna chime ...\" -My Fair Lady"},
	{Name: "Wheat", Description: "Mainly used in flour. World output of wheat is more than 600 million metric tons a year ... so someone's making a lot of dough."},
	{Name: "Wheel Of Fortune", Description: "American TV game show, BIG MONEY! BIG MONEY!."},
	{Name: "Whipped Cream", Description: "Great on strawberry shortcake, banana splits, chocolate pudding ..."},
	{Name: "Whips", Description: "\"Crack that whip ... whip it, whip it good.\" -Devo"},
	{Name: "Whoopie Goldberg", Description: "1950-, American actor and comedian. Starred in such movies as Ghost, which earned her an Academy Award. Whoopee!"},
	{Name: "Will Smith", Description: "1968- , Successful American rap star, TV star and wildly successful motion picture star. He's got it all. We hate him."},
	{Name: "William Shakespeare", Description: "1564-1616, The English poet and playwright. And all the world IS a stage ..."},
	{Name: "Wimbledon", Description: "Strawberries ... cream ... temper tantrums ..."},
	{Name: "Windsurfing", Description: "Really just surfing for lazy people."},
	{Name: "Wine Tasting", Description: "Spit or swallow?"},
	{Name: "Winning The Lottery", Description: "The more you play, the more THEY win."},
	{Name: "Witch Hunts", Description: "Popular locations: Salem, Massachusetts and Washington, D.C."},
	{Name: "Women", Description: "REAL Women."},
	{Name: "Women's Soccer", Description: "The 1999 World Cup finals was the most-watched women's sporting event in history."},
	{Name: "Wood Chippers", Description: "\"I guess that was your accomplice in the wood chipper.\" -Marge Gunderson, Fargo"},
	{Name: "Woodstock", Description: "The 1969 love, music and mud festival attended by 400,000. Or, the little yellow bird."},
	{Name: "Woody Allen", Description: "1935- , American comedian, actor and director, of Bananas, Annie Hall, Hannah and Her Sisters, and lots of New York Stories."},
	{Name: "Worms", Description: "\"A man may fish with the worm that hath eat of a king, and eat of the fish that has fed of that worm.\" -\"Hamlet\" Shakespeare"},
	{Name: "X-Ray Vision", Description: "Available to Superman -for emergency use only."},
	{Name: "X-Rays", Description: "X-Rays were discovered in 1895 by the German physicist Wilhelm Conrad Roentgen. Now if they could just get those X-ray glasses down."},
	{Name: "Yellowstone Park", Description: "Home to 3000 geysers and hot springs. More gas and hot air than Washington, D.C."},
	{Name: "Zen", Description: "Japanese form of Buddhism, originated in China. Zen again, maybe not."},
	{Name: "Zucchini", Description: "A squashed vegetable. "},
}
